### ISSUE TITLE
kcf

### ISSUE THREAD

**Issue by KANG-Z** [DHNicoles/KCF#1]
Hello, is this the realization of multi-target tracking?Thank you for your reply !

**Comment by DHNicoles** [comment]
Sorry for not answering in time, this version can only support single-target tracking, but you can easily implement multi-target tracking by instantiating multiple KCF objects.

**Comment by DHNicoles** [comment]
@KANG-Z  Sorry for not answering in time, this version can only support single-target tracking, but you can easily implement multi-target tracking by instantiating multiple KCF objects.

**Comment by DHNicoles** [comment]
done.
